### ISSUE TITLE
Errors compiling Sturmflut

### ISSUE THREAD

**Issue by GravitySandwichh** [TobleMiner/sturmflut#3]
Quick rundown of what i tried:

- CentOS, Fedora, Ubuntu and Debian
- Always running into the exact same Magickwand error
- Tried numerous versions of Imagemagick from both their website and repo's
- Tried removing version check

Nothing helped. Am i doing something wrong?

`rm -f sturmflut
/bin/sh: 1: pkg-config: not found
gcc -Ofast -Wall -march=native -DIMAGICK= image.c network.c main.c progress.c -lpthread `pkg-config --cflags --libs MagickWand` -o sturmflut
/bin/sh: 1: pkg-config: not found
In file included from image.c:9:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from network.c:21:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from network.h:10,
                 from main.h:4,
                 from main.c:20:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:10: sturmflut] Error 1
`

Kind Regards,
Paul

**Comment by TobleMiner** [comment]
Hey, looks like IMAGICK is not properly defined. Maybe you are missing pkg-config?

**Comment by TobleMiner** [comment]
I've updated the readme to include pkg-config in the list of dependencies. Has installing pkg-config resolved the issue?

**Comment by GravitySandwichh** [comment]
Sorry for my late response. I just installed pkg-config but still got the same error. Do i have to configure something with pkg-config? I'm using the latest imagemagick from the imagemagick website btw. Same error when using the one from the Ubuntu repo.

**Comment by TobleMiner** [comment]
Not really. `/bin/sh: 1: pkg-config: not found` just implied to me that pkg-config is missing. pkg-config is simply a query tool to get the required cflags and ldflags for build dependencies. It is possible that pkg-config does not detect your imagemagick if it is manually installed. Please try the version from the official Ubuntu repo. With Ubuntu you will need to install the dev package `libmagick-dev`, too.

**Comment by GravitySandwichh** [comment]
Just did that. Still seems that it doesn't want to compile. It does say now that it can't find magickwand though. Got the following error:

Package ImageMagick was not found in the pkg-config search path.
Perhaps you should add the directory containing `ImageMagick.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ImageMagick' found
gcc -Ofast -Wall -march=native -DIMAGICK= image.c network.c main.c progress.c -lpthread `pkg-config --cflags --libs MagickWand` -o sturmflut
Package MagickWand was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickWand.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickWand' found
In file included from image.c:9:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from network.c:21:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from network.h:10,
                 from main.h:4,
                 from main.c:20:
image.h:6:13: error: operator '<' has no left operand
 #if IMAGICK < 7
             ^
image.h:9:11: fatal error: MagickWand/MagickWand.h: No such file or directory
  #include <MagickWand/MagickWand.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:10: sturmflut] Error 1

**Comment by TobleMiner** [comment]
Hey,

sorry for taking so long to get back to you. CCCamp 2019 had me pretty busy during the last two weeks.

I've just tried building on a fresh Ubuntu Disco Dingo install. After installing the following packages building worked just fine:

- pkg-config
- libmagick++-dev
- libmagickwand-dev

I'll add this to the README to avoid future confusion. Please let me know if this fixed it for you.

**Comment by GravitySandwichh** [comment]
That works! Thanks!

**Comment by TobleMiner** [comment]
Nice. Glad I could help.
